apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servicegraphs.service.graph.com
spec:
  group: service.graph.com
  scope: Namespaced
  names:
    plural: servicegraphs
    singular: servicegraph
    kind: ServiceGraph
    shortNames:
      - sg
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            specs:
              type: object
              properties:
                nodes: 
                  type: array
                  items:
                    type: object
                    properties:
                      name: 
                        type: string
                      port:
                        type: integer
                      replicas:
                        type: integer
                      resources:
                        type: object
                        properties:
                          requests:
                            type: object
                            properties:
                              memory:
                                type: string
                              cpu:
                                type: integer
                          limits:
                            type: object
                            properties:
                              memory:
                                type: string
                              cpu:
                                type: integer
                      apiEndpoints:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            path:
                              type: string
                            cpuLoad:
                              type: integer
