# permissions for end users to view servicegraphs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicegraph-viewer-role
rules:
- apiGroups:
  - onlab.example.com
  resources:
  - servicegraphs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - onlab.example.com
  resources:
  - servicegraphs/status
  verbs:
  - get
