apiVersion: "service.graph.com/v1"
kind: ServiceGraph
metadata:
  name: my-service-mesh
specs:
  nodes:
    - name: front-end
      port: 80
      nodePort: 30001
      replicas: 1   
      resources:
        requests:
          memory: 64mb
          cpu: 100
        limits:
          memory: 125mb
          cpu: 200
      apiEndpoints:
        - name: instant
          path: /instant
          cpuLoad: 100
          delay: 10
          callOut: "pass"
        - name: chain
          path: /chain
          cpuLoad: 200
          delay: 20
          callOut: "back-end:80/profile"
        - name: iterate
          path: /iterate
          cpuLoad: 300
          delay: 30
          callOut: "back-end:80/profile__monitor:80/index"

    - name: back-end
      port: 80
      replicas: 3   
      resources:
        requests:
          memory: 64mb
          cpu: 100
        limits:
          memory: 125mb
          cpu: 200
      apiEndpoints:
        - name: profile
          path: /profile
          cpuLoad: 100
          delay: 10
          callOut: "db:80/get"
        - name: create
          path: /create
          cpuLoad: 200
          delay: 20
          callOut: "db:80/set"

    - name: db
      port: 80
      replicas: 1   
      resources:
        requests:
          memory: 64mb
          cpu: 100
        limits:
          memory: 125mb
          cpu: 200
      apiEndpoints:
        - name: get
          path: /get
          cpuLoad: 100
          delay: 10
          callOut: "pass"
        - name: set
          path: /set
          cpuLoad: 200
          delay: 20
          callOut: "pass"

    - name: monitor
      port: 80
      replicas: 1   
      resources:
        requests:
          memory: 64mb
          cpu: 100
        limits:
          memory: 125mb
          cpu: 200
      apiEndpoints:
        - name: index
          path: /index
          cpuLoad: 100
          delay: 10
          callOut: "pass"
